### ISSUE TITLE
Optional hover text other than "caption"

### ISSUE THREAD

**Issue by halogenica** [liwenyip/hugo-easy-gallery#1]
As per our discussion here: https://github.com/halogenica/beautifulhugo/pull/35#issuecomment-289880211

It would be nice to be able to define hover text that is different from the caption; for example when the captions are very long. One idea is to prefer to show the "alt" text when hovering, and fall back to "caption" if "alt" is not provided, or no hover text if neither are provided. I want to make sure this is reasonably expected behavior..

**Comment by liwenyip** [comment]
Thanks @halogenica 

Having thought about this, it would actually be easier to leave the hover captions as they are, and instead have ***PhotoSwipe*** prefer `alt` if set.

This is because the hover caption text needs to be contained in a css-stylable element, i.e. `<figcaption>` or a `<div>`, whereas PhotoSwipe can pull its captions from any attribute of any element including the `<img>` `alt`.

**Does that sound sensible?**

The alternative would be to change the `{{< figure >}}` shortcode to put the `alt` param inside `<figcaption>` and the `caption` param inside the `<img>` `alt` which is just confusing...

**Comment by liwenyip** [comment]
Implemented in https://github.com/liwenyip/hugo-easy-gallery/commit/f0e6d5d62f58284beadf98db71861af90f2cff8e
