### ISSUE TITLE
Captions lose capital letters

### ISSUE THREAD

**Issue by jghauser** [liwenyip/hugo-easy-gallery#16]
Thanks a lot for this great tool! I'm using it on my website and it's working really well. The only minor issue I have is that when I'm adding a whole directory and have the captions depend on the file name, captions have the first letter capitalised and the rest in small (e.g. "This is a photo from russia"). This is the case even if the filename has capitals (e.g. "This-is-a-photo-from-Russia.jpg"). Any idea what's up there?

**Comment by liwenyip** [comment]
It's because I've used the [humanize](https://gohugo.io/functions/humanize/) function to convert the filename to a caption. 

'humanize` is a good function for converting machine-readable strings to human-readable, but unfortunately it doesn't retain the original upper/lower case.

To get the behaviour you want (replace dashes with spaces), go to layouts\shortcodes\gallery.html:18 and replace `humanize` with `replaceRE "\-" " "`. (I haven't tested this - could you please let me know if it works.)

**Comment by jghauser** [comment]
Thanks a lot! I got it to work with `replaceRE "[_-]" " "`. Your version gave me an error, I think because escaping is unnecessary.

**Comment by seanburlington** [comment]
Cool - this worked for me too :-)
