### ISSUE TITLE
Problem with Dimension Theme Ft. Hugo Easy Gallery

### ISSUE THREAD

**Issue by TheDudeBMF** [liwenyip/hugo-easy-gallery#19]
I’m implementing the Hugo Easy Gallery on my site but I have a problem with it in combination with the Dimension theme.

I run the gallery on this page: http://newsite.luckycharmtattoo.nl/#portfolio
When I click one of the images, the gallery doesn’t go full screen, but it seems ‘caputered’ in the underlaying layer of the theme. 
![Screenshot](https://user-images.githubusercontent.com/35812333/35402026-8efd6b76-01fb-11e8-9c57-a10c49b58a26.png)

Because of this, the gallery doesn’t go to the center of the display and doesn’t scale. Does someone know how I can avoid this so the gallery works as good as on the authors website?

**Comment by liwenyip** [comment]
Not sure what's going on here - the key css attributes that needed to make the photoswipe gallery go full screen are `position: fixed;`, `width: 100%;`, `height: 100%;`, `left: 0;`, and `top: 0;`, and none of these have been overridden by your theme.

![image](https://user-images.githubusercontent.com/16456010/35421757-0db495b4-0299-11e8-82d1-43709b3f191b.png)

Have you had a look at the [PhotoSwipe issues](https://github.com/dimsemenov/PhotoSwipe/issues) to see if anyone else had had a similar issue? 

Otherwise you could try asking a question on StackExchange.

**Comment by TheDudeBMF** [comment]
Thanks for looking in to this! I will go to the PhotoSwipe issues and StackOverflow.
