### ISSUE TITLE
Outdated jQuery Version

### ISSUE THREAD

**Issue by acahir** [liwenyip/hugo-easy-gallery#45]
Why are you including such an old version of jQuery (1.12.4) in `load-photoswipe.html`? Current version is 3.3.1, so that's two major versions behind.

Considering PhotoSwipe doesn't require jQuery, could also just use vanilla js.

**Comment by liwenyip** [comment]
Hi @acahir 

There was probably a reason why I used that version of jQuery but I can't for the life of me remember what that reason was... I used jQuery instead of vanilla js because I'm not a web developer (I currently work as a construction project manager) and jQuery was easier to grok at the time.

Migrating to vanilla js has been addressed in #27 and will probably happen eventually :-)

Regards,
Li-Wen
