### ISSUE TITLE
A container remains visible and blocking after "close"

### ISSUE THREAD

**Issue by andrekosak** [liwenyip/hugo-easy-gallery#6]
I have just clone a **Gitlab Pages** project build with Hugo, where the gallery plugin is a part of theme.

The gallery looks nice and pretty. But I got stuck on a bug: after clicking on a image, then closing it (hitting on a background or a close-button), the page layout gets blocked with a gallery-container with a class `pswp`.

Could you please check [this page](https://pages.gitlab.io/hugo/post/2017-03-20-photoswipe-gallery-sample/)?

You can find source code of the page here https://gitlab.com/pages/hugo

**Comment by MartinVerges** [comment]
I got the same bug, dunno at the moment why or how to fix it.

**Comment by halogenica** [comment]
I have the same exact problem.

**Comment by halogenica** [comment]
Turns out the reason this happened in my code is because I was including the load-photoswipe.js code twice, which resulted in registering the on click callback twice. This was entirely my fault because I manually loaded the load-photoswipe.js script in my footer in addition to using the load-photoswipe shortcode. This could most easily be solved by either removing the script in my footer, or using the load-photoswipe-theme shortcode instead. 

I chose to fix it by always loading photoswipe and not using either of those shortcodes. I moved the load-photoswipe-theme shortcode to the partials folder, included that partial in the head, and continued to load the scripts in the footer. 

I can confirm once I fixed my bug, things worked as expected. So you may want to double check your code for the on click function being registered twice, etc.

**Comment by liwenyip** [comment]
Perhaps I should put something in load-photoswipe.js to prevent the callback being registered twice.

**Comment by liwenyip** [comment]
I've added a check to load-photoswipe.js that will alert you if you've loaded the js file twice.

If you're going to load the js files in the footer, make sure you follow the instructions at https://github.com/liwenyip/hugo-easy-gallery#theme-integration

The main point is: if you are going to load the js files in the footer of your theme, you need to comment out the `<script>` tags in the `load-photoswipe` shortcode (or use the `load-photoswipe-theme` shortcode).
